stages:
  - image
  - deploy

.docker_login: &docker_login
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

Build image:
  stage: image
  only:
    - develop
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  before_script:
    - *docker_login
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

Update in K8s:
  image: docker:latest
  stage: deploy
  only:
    - develop
  # when: manual
  services:
    - docker:dind
  before_script:
    - apk add curl git
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    - kubectl version --client
    - kubectl config use-context digedu/campus-june-2022/gitops-test:sferum-dev
    - kubectl config set-context --current --namespace=app-campus-june-2022
  script:
    - kubectl set image deployment/campus-whattime-frontend frontend=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
